### ISSUE TITLE
Missing dependency adm-zip

### ISSUE THREAD

**Issue by trycrmr** [aws-samples/cloudfront-authorization-at-edge#1]
Summary: Fresh clone following the build steps for [Option 2](https://github.com/trycrmr/cloudfront-authorization-at-edge#option-2-deploy-with-sam-cli) fails on third step. "adm-zip" dependency is missing. 

From CONTRIBUTING.md

"A reproducible test case or series of steps": `git clone` then `npm i` then `npm run build`
"The version of our code being used": Master as of [this commit](https://github.com/aws-samples/cloudfront-authorization-at-edge/commit/9c83b08b89f7f0edeee199fc8f2d49a9df4ab767)
"Any modifications you've made relevant to the bug": No modifications made. 
"Anything unusual about your environment or deployment": Here's a useful output [gatsbyjs's CLI](https://github.com/gatsbyjs/gatsby) produced about my environment...

>    System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-7100H CPU @ 3.00GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.10.0/bin/npm
  Languages:
    Python: 3.6.3 - /home/public/.pyenv/shims/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
  npmGlobalPackages:
    gatsby-cli: 2.7.8

**Comment by trycrmr** [comment]
`npm i @types/adm-zip` appears to resolve the issue. Looks like it installs the required package and the type definitions.

**Comment by ottokruse** [comment]
Thanks for finding this, logging it and creating a PR! I just commented on your PR

**Comment by ottokruse** [comment]
Resolved by #2
