### ISSUE TITLE
[Enhancement] Redirect trailing / pages to index.html

### ISSUE THREAD

**Issue by gekart** [aws-samples/cloudfront-authorization-at-edge#100]
Some CMSes (like hugo) are using links with trailing slashes with the expectation of `index.html` path extension semantics. E.g. `example.com/test/` is expected to return `example.com/test/index.html` CloudFront does not support this oob on anything but the root level. However, `index.html `extensions in subfolders is the usual behavior of the S3 website functionality. Here we cannot resort to using S3 web hosting, since we don't want to publish an S3 site.

I solved this in my basic-auth solution with a short snippet like the second solution here:
https://stackoverflow.com/questions/49082709/redirect-to-index-html-for-s3-subfolder

It should be a quick fix. I can do it if its accepted.

**Comment by gekart** [comment]
I think the best way to implement this is by creating a Origin Request lambda (that one is still available to be used) according to https://aws.amazon.com/de/blogs/compute/implementing-default-directory-indexes-in-amazon-s3-backed-amazon-cloudfront-origins-using-lambdaedge/

**Comment by ottokruse** [comment]
Thanks for mentioning this use case and linking to that solution.
To keep Auth@Edge as simple as possible, I think this would not need to be a functionality to be included by default. But for sure it is good to mention it here.

Another approach that would work is to upload those index.html files to the exact S3 path you'd want, and utilize the fact that object keys on S3 may end with a slash:
/my/sub/folder/index.html --> s3://mybucket/my/sub/folder/ (so the key would be "/my/sub/folder/")

That would save you a Lambda@Edge invocation.

**Comment by gekart** [comment]
Well the point is that I don't think this is how Hugo works (at least to my knowledge).

But you are right: The solution can be added on top of this application, since the "Origin request" lambda is still free to add. In my first post I still had the assumption that one would need to add the functionality to one of the provided lambdas.
