### ISSUE TITLE
Should refresh_auth validate the nonce hmac?

### ISSUE THREAD

**Issue by RLuckom** [aws-samples/cloudfront-authorization-at-edge#113]
Thanks for this example; it's been really helpful for me as I try to get a deeper understanding of oauth.

From my reading of the code, it appears that the [refresh_auth](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/src/lambda-edge/refresh-auth/index.ts) doesn't ever actually use the nonce hmac cookie to validate that either the original nonce (cookie) or the querystring nonce was actually signed with the nonce signing secret. Since there _is_ a [test that those nonces match](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/src/lambda-edge/refresh-auth/index.ts#L147), it seems like we _are_ concerned with some kind of verification there.

I may be misreading the code or missing something about oauth, but I wanted to ask the question just in case.

**Comment by ottokruse** [comment]
I think you are right and have spotted a place where we could (should) also use nonce signing.

Some context to understand how important this is:
- Using nonces is an OAuth recommended practice
- Signing the nonces is a security-in-depth measure (that we added later, after launching this Auth@Edge sample solution)

By signing the nonce, we can be sure that *we* were the ones creating them. That should make it super duper hard for other (malicious) websites to redirect you halfway into the auth-flow. Even without signing it's gonna be a tough trick for the other websites to "inject" a nonce cookie to begin with.

Do you maybe want to collaborate on the project and add the nonce signing & verification to the refresh auth flow?

**Comment by RLuckom** [comment]
I'm too busy to take that on right now but if that changes I'll let you know!
