### ISSUE TITLE
Change the User Pool

### ISSUE THREAD

**Issue by dmt0768** [aws-samples/cloudfront-authorization-at-edge#118]
Hi!

I need to change the User Pool of the already created application on my one. What are the proper ways to do this?

**Comment by dmt0768** [comment]
I solved the problem by this way. I fully removed my application via CloudFormation and then I again deployed one but with custom settings. It is possible to set any of your pools.

**Comment by ottokruse** [comment]
Ok great to hear!

Deploying a new version on top of your previous one, with changed parameters, would (should) also have worked. I.e. a CloudFormation stack update. But your way is the safest, because an "update" could go wrong if you mix and match different versions of the template / SAR app.
