### ISSUE TITLE
Allow user sign up

### ISSUE THREAD

**Issue by HappyDias** [aws-samples/cloudfront-authorization-at-edge#127]
First of all, I'd like to congratulate you for a very robust solution that pretty much allows me to feel safe when generating app solutions in the cloud. I've used it a lot in the past year.

I have a question regarding, as the title suggests, allowing users to sign up.

I have created a new stack, with completely new resources and everything is working properly. As I intend to allow users to sign up for the application, I edited the created cognito pool to allow users to "sign themselves up" (radio box on AWS console).

When I do this, the sign in page now provides a link to a sign up page:

![image](https://user-images.githubusercontent.com/25264603/118116097-bd4ebe80-b3e1-11eb-96de-63de72b57615.png)

I can use that link to attempt to create a new user by supplying an email and a password (according to the needs of the pool). However, instead of getting at least the acknowledgement that the application went through, I get sent to an error page, resulting of a redirect from '/parseauth'.

Now I expect that the '/parseauth' redirect is just the default behavior since there is no behavior for the /signup endpoint, My question is thus a two-parter:

- Is allowing users to sign themselves up a use case that is possible with this stack?
- If it is, what are the steps I need to take to allow this feature?

Thanks again for this stack and hope to hear from you soon

**Comment by HappyDias** [comment]
Apologies, I spoke too soon, it was merely a question of changing some settings in the Cognito user pool. Apologies for raising the issue. I'll close the issue.

For future users that might be interested, in the MFA and verifications page of the Cognito pool you are required to allow recovery (email and/or phone) and also verify the email. Both of which are disabled by default via this stack (picture attached for reference):

![image](https://user-images.githubusercontent.com/25264603/118142512-5ab9ea80-b402-11eb-89ba-19af6adfef85.png)

**Comment by ottokruse** [comment]
It seems you found a solution, great.

> First of all, I'd like to congratulate you for a very robust solution that pretty much allows me to feel safe when generating app solutions in the cloud. I've used it a lot in the past year.

Thanks!
