### ISSUE TITLE
Handle optionally permission boundaries

### ISSUE THREAD

**Issue by Leooo** [aws-samples/cloudfront-authorization-at-edge#128]
Hello, to consume this repo in our organization I've created a fork that allows optionally adding permissionBoundaries to roles. I'd like to create a PR for it to this repo - could you give me access please? [See PR](https://github.com/centrica-engineering/cloudfront-authorization-at-edge/pull/2) Thanks

**Comment by ottokruse** [comment]
Sounds good! Should be open already for PRs though?? We have received many PRs already.

**Comment by Leooo** [comment]
Indeed, done in https://github.com/aws-samples/cloudfront-authorization-at-edge/pull/129 thanks - closing this issue
