### ISSUE TITLE
Sign-in Issue

### ISSUE THREAD

**Issue by hyphen1370** [aws-samples/cloudfront-authorization-at-edge#134]
Hello, 

I was deployed this into my own AWS account in us-east-1 by using option 1. I didn't change any options except changing the log level from none to error. After that, I created a test user in cognito user pool it created. After logging in, it gives me this error:

We can't sign you in because of a technical problem

 Error: Failed to exchange authorization code for tokens: Error: Request failed with status code 400 [log region: us-west-2]

What might be causing it?

Thanks

**Comment by ottokruse** [comment]
Can you take a look at the logs for the ParseAuth handler Lambda function in region us-west-2 ?
Does it reveal more information?

**Comment by hyphen1370** [comment]
It was my failed to not map the nameID with email since that is default username attribute
