### ISSUE TITLE
exclude root path for login

### ISSUE THREAD

**Issue by hyphen1370** [aws-samples/cloudfront-authorization-at-edge#138]
Hello, 

Are there any options to exclude the root path to automatically redirect for login? 

After deploying using option 1, I can add the new path in Cloudfront like /test/test2/*. When I go to https://xxx.cloudfront.net/test/test2/index.html. It goes there without login. So, I would like to have https://xxx.cloudfront.net/ to be the main page for users to select where they want to go next. When they click on the hyperlink that points to a path that requires login, then ask for login. Is there any way to do this? 

Thanks

**Comment by ottokruse** [comment]
You can achieve what you want (if I understand it correctly) by using different CloudFront behaviors, with a different precedence.

E.g.:

1. Precedence 1 (will be used first if it matches): path pattern /some/path/that/requires/signin
2. Precedence 2 (will be used if 1 does not match): path pattern / (or just use "*" here, as the default behavior)

Then, associate the checkAuth Lambda to 1 but not to 2. Thereby protecting 1, but not 2.

Note that in de default deployment of this solution, the checkAuth Lambda is associated with the default behavior. But you can go in and change that.

Note also, you can deploy this solution with setting "CreateCloudFrontDistribution" to "false", then you;'ll just get the Lambda@Edge functions, that you can wire into your own CloudFront Distribution as you see fit. (Is explained in some more detail in the README, and the reuse folder has an example)

Hope that helps?
