### ISSUE TITLE
CreateCloudFormationTemplate Permission errors

### ISSUE THREAD

**Issue by oatrevdev** [aws-samples/cloudfront-authorization-at-edge#145]
I am getting the following error when add this into my recent CFT

   MyLambdaEdgeProtectedSpaSetup:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge
        SemanticVersion: 2.0.9

."..is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-lambda-edge-cognito-auth"

**Comment by ottokruse** [comment]
Looks like the AWS IAM User/Role that you are using when you are trying to deploy does not have the right IAM permissions.

However looking at the docs, it's not mentioned that you would need "serverlessrepo:CreateCloudFormationTemplate":

- https://docs.aws.amazon.com/serverlessrepo/latest/devguide/security_iam_id-based-policy-examples.html
- https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-api-permissions-ref.html

It might be an omission in the docs.

Can you try adding "serverlessrepo:CreateCloudFormationTemplate" on resource "*" (or if you want, more specific "arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-lambda-edge-cognito-auth") to your IAM permissions and try again?

**Comment by oatrevdev** [comment]
that did the trick, thank you.
