### ISSUE TITLE
Can't create Cognito User Pool when deploying the stack

### ISSUE THREAD

**Issue by pjvilloud** [aws-samples/cloudfront-authorization-at-edge#150]
I'm trying to deploy this stack to enable cognito user login for my static S3 hosted website but I'm getting this error : 

> The following resource(s) failed to create: [CognitoUserPool]
> The following resource(s) failed to create: [CreateUserPoolAndClientFunction]

![image](https://user-images.githubusercontent.com/31385588/130998242-e481ce98-3c2e-409e-a603-f5f552270940.png)

I left all the default options.

Any idea about what is causing this ? I'm using an account created from my AWS organization 

Thanks !

**Comment by pjvilloud** [comment]
Indeed, it's better maintained and I deployed it without any problem thanks ! Just a question though (maybe it needs its own issue), is it possible to redirect the user on different S3 buckets if he is in a specified group ?
Example :
User johndoe (he is in group 1) => bucket B1
User janedoe (she is in group 2) => bucket B2

Thanks !

**Comment by ottokruse** [comment]
>  I deployed it without any problem thanks
Great!

> is it possible to redirect the user on different S3 buckets if he is in a specified group
Not out of the box, you'd have to code that.

Using an origin request lambda as described [here](https://aws.amazon.com/blogs/networking-and-content-delivery/dynamically-route-viewer-requests-to-any-origin-using-lambdaedge/) (you probably know this already)

**Comment by pjvilloud** [comment]
Thanks for your quick answer, I'll look into it !
