### ISSUE TITLE
Authorization @ Edge Error

### ISSUE THREAD

**Issue by rps-repo** [aws-samples/cloudfront-authorization-at-edge#152]
I have used this on another account in the past with no issues but when creating this in a new account I am unable to complete the login.  The error states:

` Error: Failed to exchange authorization code for tokens: Error: Status is 400, expected 200 [log region: us-east-2]`

One thing odd about the error is it makes reference to us-east-2 but app is in us-east-1.   Also, when creating this app it will not set the alternate  domain name in cloudfront.  I have to set it and the SSL cert manually.  Not a big deal except If I need to update something in cloudformation it removes the alternate domain name and SSL cert from the distribution. 

I have deleted the stack and created it again three times with same result each time.

**Comment by ottokruse** [comment]
The log region is just where Lambda@Edge happens to run, can be anywhere on the globe. It is useful to know where it is as you can then track down the Lambda logs, in CloudWatch Logs in that region. Would be good to have a look there and see if there's more info there.

400 from Cognito while exchanging code for tokens means Cognito thinks something is not right, so it would be good to see the exact POST request to Cognito. If you set parameter LogLevel to "debug" while deploying the stack you'll get more info about the error in the POST request in the logs.

400 I've see reported here before had to do with some conflicting set up in Cognito. Such as:
- Using a client with a secret but running the deployment with EnableSpaMode = true
- Federating to another IDP, but not having proper attribute mappings

See this search: https://github.com/aws-samples/cloudfront-authorization-at-edge/issues?q=is%3Aissue+400

Turning LogLevel to debug should help hopefully in finding your specific cause.

> Also, when creating this app it will not set the alternate domain name in cloudfront. I have to set it and the SSL cert manually.

About that issue, would you mind creating a separate issue for it, with a sample CFN template, or explanation on how you deploy it exactly, so we can reproduce?

**Comment by rps-repo** [comment]
The cognito client did have a secret set so that was the issue with the 400 error.  I am able to log in OK now.
I will create another issue on the problem with the alternate domain name.
Thanks!
