### ISSUE TITLE
Login failed using existing Cognitor User Pool

### ISSUE THREAD

**Issue by zhuw2021** [aws-samples/cloudfront-authorization-at-edge#153]
Hi,
I am trying the solution with the existing Cognitor User Pool, which uses cooperate SSO PingFed. The attribute mappings are
cn=>Name
sn=>Family Name
Email=>Email
xxid=>Username

After the provided the xxid/password from the login page, got the following message:
Sign-in issue
We can't sign you in because of a technical problem

 Error: [Cognito] server_error: Error in SAML response processing: Invalid user attributes: username: Attribute does not exist in the schema. [log region: us-east-1]

Tried to add mapping username=>Username, still got the same error message.

**Comment by ottokruse** [comment]
Hi! Make sure to also add all the fields you map to the User Pool field schema. Add the right custom fields under General Settings > Attributes

**Comment by zhuw2021** [comment]
Hi Otto, thanks for getting back to me. I added all fields to the custom attributes:

Custom attributes custom:cn, custom:sn, custom:xxid, custom:username

I still got the same error message.

**Comment by ottokruse** [comment]
Maybe better not map to "username" attribute, as it is a special field, better try preferred_username or so?

Other than that hunch, I need more info to help you -- explain the steps to reproduce this issue please.

**Comment by zhuw2021** [comment]
Here are the steps I setup Cogito User Pool with SAML PingFederate
1. Created User Pool with default setting
2. From Federation, Identity Providers, --> SAML
3. Uploaded provided metadata XML file and created provider
4. Go to Federation --> Attribute mapping (the company standard of  integration Cognito with SSO PingFed)
cn <=> Name
sn <=>Family Name
Email <=> Email
xxid <=> Username

5. Enabled the Provider Name from App Client Settings
6. Fill in Callback URL/Sign Out URL
7. enable Allowed OAuth Flows:Authorization code grant,Implicit grant
8. enable Allowed OAuth Scopes: phone, email, openid, aws.cognito.signin.user.admin, profile

After the cognito user pool was registered to PingFed, I was able to use Hosted UI to trigger the SSO login page and load the Callback URL.

Then I deployed the solution from Serverless Application Repository, provided User Pool's ARN and App client ID so that I can reuse the existing user pool.

The Cloudfront distribution, S3, lambda function etc. were created successfully. The https://xxxx.cloudfront.net/parseauth URL was added to the Callback URL field. Then when I tried to load the distribution URL, I got the SSO login page first, provided the useID and password, then I got the error.

Looks like 'username' attribute (lower case) is default attribute. We had a mapping xxid <=> Username, as required by company standard. Is there a conflict here? Or do we need to add attribute 'username' on PingFed server side?

**Comment by ottokruse** [comment]
> Looks like 'username' attribute (lower case) is default attribute. We had a mapping xxid <=> Username, as required by company standard. Is there a conflict here?

Better not map to `username` - that is a field that Cognito determines itself. Use another field (at least to test and see if that resolves your issue), e.g. use the field `preferred_username` to map to.

> Or do we need to add attribute 'username' on PingFed server side?

You shouldn't need to make any changes there.

**Comment by zhuw2021** [comment]
Hi Otto, I mapped the xxid <=> Preferred User Name from the console. Now I got:

 Error: Failed to exchange authorization code for tokens: Error: Status is 400, expected 200 [log region: eu-central-1]

**Comment by ottokruse** [comment]
400 from Cognito while exchanging code for tokens means Cognito thinks something is not right, so it would be good to see the exact POST request to Cognito. If you set parameter LogLevel to "debug" while deploying the stack you'll get more info about the error in the POST request in the logs.

400 I've see reported here before had to do with some conflicting set up in Cognito. Such as:

- Using a client with a secret but running the deployment with EnableSpaMode = true
- Federating to another IDP, but not having proper attribute mappings

See this search: https://github.com/aws-samples/cloudfront-authorization-at-edge/issues?q=is%3Aissue+400

Turning LogLevel to debug should help hopefully in finding your specific cause.

**Comment by zhuw2021** [comment]
Hi Otto, it is working for me now. I created another app client without client secret with EnableSpaMode=true, then it worked. Thanks again for all your help!

**Comment by ottokruse** [comment]
Awesome!
