### ISSUE TITLE
lambd@edge function are not working

### ISSUE THREAD

**Issue by surendarkaniops** [aws-samples/cloudfront-authorization-at-edge#155]
we just clone this repo and we have created the individual lambda functions and associate with cloudfront. 

Brief description:
we have created the cloudfront and S3 bucket. we are able to access the site using cloudfront URL
we have added the A record in route53 for cloudfront URL. we are able to access the site using custom domain

now we have cloned this repo to create the lambda@edge functions (we are not using Serverless function).
we have created the lambda functions with the appropriate source_uri (mentioned in template.yaml file)
we have associated the lambda@function with cloudfront. now we are not able to access the site

More info:
when lambda created through cloudformation or SAM configuration.json & bundle.js files are created in lambda function but configuration.jon & bundle.js files is not available when created though manually.

we are actually trying to complete this setup using terraform.

**Comment by ottokruse** [comment]
> configuration.jon & bundle.js files is not available when created though manually.

Right, configuration.json is injected by a CloudFormation custom resource.
bundle.js should be created by running `npm run build`. You need to run webpack to get them.

**Comment by ottokruse** [comment]
Sounds like you're having quite a different/custom setup, so it might be hard to support you.

**Comment by surendarkaniops** [comment]
Where npm built is happening in template file.???? 

If I take a copy of src directory and run npm build manually can I get rendered code for 5 lambda@edge functions???? 


How do I can get the code alone to reuse ??? 

I am deploying this through terraform setup, so if you could provide the code in zip file will be helpful. 

I think only 5 lambda function is enough to complete the setup am I right..???? Bcoz other lambda functions are code update functions.  If I manually create the lambda functions with rendered code in zip file I don't need that code update functions am I right??? 

Can you please provide the code for reuse

**Comment by ottokruse** [comment]
Closing for now, as the required support is beyond the scope of this sample repo.
If there's any concrete and specific questions that cannot be answered by README.md or exploration of this repo, let me know.
