### ISSUE TITLE
`aws-jwt-verify` unavailable because of private registry 

### ISSUE THREAD

**Issue by timmeinerzhagen** [aws-samples/cloudfront-authorization-at-edge#159]
With #157 the npm package `aws-jwt-verify` was introduced. 

The package lock seems to try pulling this via this url under a private registry: 
[`https://f1-video-archive-495910770749.d.codeartifact.eu-west-1.amazonaws.com:443/npm/video-archive/aws-jwt-verify/-/aws-jwt-verify-1.0.1.tgz`](https://f1-video-archive-495910770749.d.codeartifact.eu-west-1.amazonaws.com:443/npm/video-archive/aws-jwt-verify/-/aws-jwt-verify-1.0.1.tgz). 

This is not available publicly and as such `npm install` fails. 

Shouldn't this refer to the official source in the npmjs registry entry [`aws-jwt-verify`](https://www.npmjs.com/package/aws-jwt-verify)?

**Comment by ottokruse** [comment]
Thanks for reporting, just fixed it while updating dependencies at the same time.

**Comment by ottokruse** [comment]
Ran into a rabbit hole of TypeScript issues with the dependency update but should all be (really) fixed now, by #162
