### ISSUE TITLE
Node Js Auth Header

### ISSUE THREAD

**Issue by navilwayne** [aws-samples/cloudfront-authorization-at-edge#17]
Team
I don't want to trigger multiple lambda. Can we do all stuff in single lambda & can we get authorization header after login to Cognito to Cloudfront 
I am referring below example, but i am not getting header after successful log in from AWS Cognito 

Example 
https://github.com/aws-samples/authorization-lambda-at-edge/blob/master/node/lambda-edge-function/index.js

Or can share reference code in Node js for parse-auth

**Comment by ottokruse** [comment]
Please clarify your issue, maybe you posted it to the wrong repo? The repo you posted the link of, is for another implementation, that uses HTTP headers to pass JWT's from client to Lambda@Edge. This repo here uses cookies for that, not HTTP headers.

**Comment by ottokruse** [comment]
Added link to the other repo to README.md and explained difference in #27 

Closing this issue now
