### ISSUE TITLE
[Feature Request] Support bringing a Cognito User Pool from another AWS Account

### ISSUE THREAD

**Issue by ottokruse** [aws-samples/cloudfront-authorization-at-edge#171]
When bringing an existing client and setting parameter `EnableSPAMode=false`, a lookup will be done against the User Pool Client to figure out the client secret to use. This only works within the account itself.

Possible solution?: add Client Secret as parameter.

**Comment by shchambe** [comment]
This is where I'm stuck right now.  This is our scenario, but it is not recognizing the fact we even though we set EnableSpaMode to false, using a static site for S3, and passing in parameter overrides for UserPoolArn, UserPoolClientId, and UserPoolGroupName, it's still trying to create and use a cognito pool within the same account as the deployment, whereas the cognito pool is in another account.  Was this ever solved?

**Comment by ottokruse** [comment]
Had a look and another reason this doesn't work, is that the existing User Pool's domain is looked up, which also only works within the account itself:

https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/3a79edd78fc4646f7120088bab065e3a90dcbe8b/template.yaml#L614-L621

This needs some dev work in this solution:

- UserPoolDomain should be added as stack parameter, to be able to skip the lookup (for both static site mode and SPA mode)
- ClientSecret should be added as stack parameter, to be able to skip the lookup (for static site mode)

**Comment by ottokruse** [comment]
Fixed, see comments in the PR, and info in the READM
