### ISSUE TITLE
Support for Sign-ups with custom email suffix.

### ISSUE THREAD

**Issue by ayush987goyal** [aws-samples/cloudfront-authorization-at-edge#176]
Is there a way to enable user sign-ups in this solution? 
Also, one the signups are enabled, we could use the existing pre-signup lambda functionality of Cognito to allow emails with a particular suffix.

**Comment by ottokruse** [comment]
You can certainly pull this off, if you bring your own user pool. Then you can set your user pool to allow user signup and also implement the pre-signup lambda as you mention.

See [I already have a Cognito User Pool, I want to reuse that one](https://github.com/aws-samples/cloudfront-authorization-at-edge#i-already-have-a-cognito-user-pool-i-want-to-reuse-that-one). And here's an example template that includes a custom user pool: https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/example-serverless-app-reuse/reuse-with-existing-user-pool.yaml

**Comment by ayush987goyal** [comment]
Thanks @ottokruse . I think that would be the correct way forward and I was able to test the workflow out by manually changing the policy in the user pool created by this solution.
