### ISSUE TITLE
CORS blocking subdomains

### ISSUE THREAD

**Issue by mrudnitsky-synamedia** [aws-samples/cloudfront-authorization-at-edge#179]
Hey,
I have configured the CloudFront domain to be subdomain1.example.com and I'm sending requests to an API at subdomain2.example.com.
After some research I figured out that the issue is caused by CORS blocking me since I get `Access-Control-Allow-Origin: https://subdomain1.example.com` in the OPTIONS response.
I've tried to change this configuration in the CloudFront, S3 bucket and even redeployed the stack and added `"Access-Control-Allow-Origin": "*"` to the HttpHeaders but nothing helped.

Am I missing something? How can I change that? 
Thanks!

**Comment by acidwars** [comment]
@mrudnitsky-synamedia what resolved your issue?

**Comment by ottokruse** [comment]
@acidwars if you provide more info on your situation perhaps we might be able to help.
