### ISSUE TITLE
[ ERROR ] Too many http redirects using federated social login when user is out of the UserPoolGroup

### ISSUE THREAD

**Issue by RuyOliveiraRunaHR** [aws-samples/cloudfront-authorization-at-edge#181]
Hi Guys, thank you for this great resource! Very good job.

I'm trying to use this solution with a pre-existing Cognito user pool federated with Google, and specifying a user pool group in order to not allow all user with Google account to access my static site.

When I try to access the cloudfront distribution I get redirected to Cognito and I'm able to select my Google account to log in, checking the Cognito user poll I can see that my user was correctly added to the poll, but as expected it was not added to the user pool group and this is my desired behaviour.

When the browser is redirected back to Cloudfront distribution, since the user is not in the user pool group It ends up redireted once again to Cognito and the loop starts.

I think that at the parseauth it need to check, if the token is valid but the user is out of the group it's means that the user need an  administrator action to include the user into the user pool group and allow it access. I could let the user access one specifig page where one message informing this situation is hosted.

Thanks in advance.

**Comment by ottokruse** [comment]
Hi @RuyOliveiraRunaHR 

In that scenario, the user should get an error page like this:

![image](https://user-images.githubusercontent.com/6275520/152307177-95f53117-1937-4695-ac07-0eb5a2df5357.png)

Can you confirm that works for you?

**Comment by ottokruse** [comment]
Clicking "Try Again" will redirect to this page again, unless the admin in the mean team added the user to the group in Cognito, in which case the user would be nicely redirected to the page she wanted to go to.

That message is coded here:

https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/08dc0094572934fd3331e4680cfb380e8154d088/src/lambda-edge/parse-auth/index.ts#L156-L165

This is of course an example. If you want to do something else here, like e.g. show a custom HTML page with more details, e.g. explaining the user where to actually reach the admin you code the return of  a redirect (e.g. 307) to that custom page (and make that custom page publicly accessible, but not protecting that CloudFront behavior with Auth@Edge).

**Comment by RuyOliveiraRunaHR** [comment]
Hi Otto, Thanks for you return.
Yeah, you are right! I probably did something wrong, I'm doing some more tests.

Thanks a lot.
Best,
