### ISSUE TITLE
Feature request: ability to increase memory on authorization lambdas

### ISSUE THREAD

**Issue by FredrikMeyer** [aws-samples/cloudfront-authorization-at-edge#185]
We use this solution as internal documentation, so most of the time the authorization lambdas are not warmed. The first load is always ~1s, which feels a bit slow for just text. 

I wonder if increasing the memory of these lambdas will give better initial load time. (or maybe the slow start comes from elsewhere, some caching maybe?)

If it seems interesting, I can make a PR for that.

**Comment by ottokruse** [comment]
Hi @FredrikMeyer 

Yeah sure if you can experiment and find more optimal settings for memory size that'd be great!

Also keen to understand what constitutes that ~1s. Where are we spending that time. Lambda@Edge doesn't support XRay but some well placed console.log statements might already reveal a lot.

One guess is, it is the initial downloading of the JWKS from the Cognito user pool. We could prevent that, by pre-fetching the JWKS during deployment and injecting it into the Lambda@Edge function that needs it (CheckAuth). Bit bigger PR but manageable too, if you're up for it.

**Comment by FredrikMeyer** [comment]
Oh, that it is a good point. But are we sure the JWKS don't change?

I found this comment: https://github.com/awslabs/aws-support-tools/issues/139#issuecomment-813196563 , which says that this is undocumented.

**Comment by ottokruse** [comment]
Yes the JWKS doesn't get rotated but we're not supposed to count on that as it might change.

;)

The JWT verifier we use has a feature to preload JWKS: https://github.com/awslabs/aws-jwt-verify#loading-the-jwks-from-file

If the JWKS would get rotated after that, the JWT verifier will still fetch the JWKS again.

So pre-loading the JWKS will in the best case (and for now only case) mean the JWT verifier doesn't need to fetch the JWKS. In the worst case, it will have to fetch the JWKS, like it always does now.

**Comment by ottokruse** [comment]
Preloading of the JWKS was added in #213
