### ISSUE TITLE
Question: Regarding using an existing Cognito Pool

### ISSUE THREAD

**Issue by shchambe** [aws-samples/cloudfront-authorization-at-edge#187]
Hello, first off, thanks for creating this.  I feel once I can get it working correctly, it'll be a huge time saver for me.  I'm having one particular issue, which may be more from lack of understanding than anything.  I'm leveraging the reuse-with-existing-user-pool.yaml file in the example-serverless-app-reuse section as we have an existing Cognito user pool we want to use.  I'm using this to create a static site in an S3 bucket for hosting files, and for creating the Cloudformation/Cloudfront/Lambe@Edge parts so that we can have our users authenticate in the site, then pass that authentication from a link URL to retrieve the necessary files.  When I try to deploy this using the SAM CLI, it gets to the point where I get CreateUserPool 400 when trying to create the user pool, when I supplied the UserPool ARN and ID as a parameter so it wouldn't need to create one.  Due to restrictions, the account we use doesn't have rights to create Cognito user pools, but we shouldn't need to, just use the existing one.  What am I doing wrong here?  Thanks in advance for any help.

**Comment by ottokruse** [comment]
Hi. Is the User Pool in the same account as where you're deploying too? (Doesn't work otherwise)

If you provide values for parameters `UserPoolArn` and `UserPoolClientId` then a new user pool will not be created, rather the existing one will be used. (Well, that is how it is _supposed_ to work)

Note also, in that scenario, the existing User Pool's domain name will be looked up, and the existing ClientID will be updated to reflect the new redirect URIs. It sounds like you may run into permission errors there (?), but give it a shot.

The sample template you refer to [reuse-with-existing-user-pool.yaml](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/example-serverless-app-reuse/reuse-with-existing-user-pool.yaml) __does__ create a User Pool, but _outside_ the `MyLambdaEdgeProtectedSpaSetup` app––for the purpose of demoing how you could pass an external User Pool as a parameter into the app. This is just an example, if you don't want to actually create the User Pool and Client, the simplest way to deploy the app with sam cli is to deploy the [main template](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/template.yaml), and pass the right `--parameter-overrides`.

For example:
1. TypeScript compile and run Webpack: `npm run build`
1. Run SAM build. `sam build`
1. Run SAM package: `sam package --output-template-file packaged.yaml --s3-bucket <Your SAM bucket>` (note that if you don't specify the template here, the default value will be `template.yaml` in your current working directory)
1. Run SAM deploy (this is where the override parameters are specified): `sam deploy --template-file packaged.yaml --stack-name <Your Stack Name> --capabilities CAPABILITY_IAM --parameter-overrides "UserPoolArn=<your user pool arn> UserPoolClientId=<your client id>"`

**Comment by shchambe** [comment]
Thanks so much for the reply.  Yes, the Cognito pool is in the same domain (pretty sure, I'll confirm with that team).  Good to know about the template I was using.  I figured I was misunderstanding something, so I'll stop using that template in favor of the main template as you suggested with the parameter overrides.

**Comment by shchambe** [comment]
Next Question:  I've added the UserPoolARN, UserPoolClientId and UserPoolGroupName parameter overrides, but we're still not making progress.  The issue right now seems to be around IAM Roles.  We already have an IAM Role created outside of the template we need to pass in (due to right restrictions getting away from * policies).  I'm passing that in as -role-arn <arn> but we're still seeing the following when it tries to create resources:
* Modify                                           ClientSecretRetrievalHandlerRole                   AWS::IAM::Role                                     True                                             
* Modify                                           LambdaCodeUpdateHandlerRole                        AWS::IAM::Role                                     True                                             
* Modify                                           LambdaEdgeExecutionRole                            AWS::IAM::Role                                     True                                             
* Modify                                           RandomValueGeneratorRole                           AWS::IAM::Role                                     True                                             
* Modify                                           StaticSiteHandlerRole                              AWS::IAM::Role                                     True                                             
* Modify                                           UserPoolClientUpdateHandlerRole                    AWS::IAM::Role                                     True                                             
* Modify                                           UserPoolDomainLookupHandlerRole                    AWS::IAM::Role                                     True                                             
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Is there a correct way to pass in the role so that it's not trying to modify or create the roles listed above?

Also, I am setting EnableSPAMode to false in parameter overrides because this will just be a static site S3 bucket to host files.  There was some question as to whether this will create the S3 bucket for us, or if that needs to be created ahead of time (and passed according) when setting it to static, and if so, will we also be having issues with role definitions around that.

Thanks in advance as always.

**Comment by ottokruse** [comment]
> I'm passing that in as -role-arn
> ...
> Is there a correct way to pass in the role so that it's not trying to modify or create the roles listed above?

Hi. Mmm I don't quite follow, the sample solution doesn't support passing in a pre-existing role. Can you explain how you deploy in more detail? It sounds like you use a modified version of this solution's SAM template?

> Also, I am setting EnableSPAMode to false in parameter overrides because this will just be a static site S3 bucket to host files. 

Good idea!

> There was some question as to whether this will create the S3 bucket for us

Creation of the S3 bucket is is unrelated to SpaMode, it is conditional based on the parameters you provide when deploying:

https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/3a79edd78fc4646f7120088bab065e3a90dcbe8b/template.yaml#L217-L220

In human language, the S3 bucket is only created if you pass "true" for CreateCloudFrontDistribution and don't specify CustomOriginDomainName or S3OriginDomainName

**Comment by shchambe** [comment]
Yes,  it is slightly modified.  We did have to add a few parameter fields of our own for Tags we require for any resources created in AWS (this part went into Globals too to support it), but that's the only modification we made.  As for the roles, one of the teams in charge of AWS security has made it so we can't create IAM Roles directly, but instead have to go through a process that defines roles and access to get away from just Allow: * type permissions.  So, to really allow this SAM module to do the work, we need to use that defined role to allow the template to do the needful things.  We're passing it in via the SAM CLI as a --option.  Here's an example of what we're "trying" (with the -role-arn part passing in said role and account info removed to protect the innocent): sam deploy --template-file packaged.yaml --stack-name uopx-nonprod-myresource --region us-east-1 —role—arn arn:aws:iam::XXXXXXXXXXX:role/cdk-nonprod-myresource —capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM --parameter-overrides "UserPoolArn=arn:aws:cognito-idp:us-east-1:xxxxxxxxxxx:userpool/us-east-1_fOHhdnuSW UserPoolClientId=xxxxxxxxxxxxxxxxxxxxxx
UserPoolGroupName=us-east-1_<pool ID)> Appkey=xxx ModKey=xxxxxxxxxxx CreatedBy=<email address> PermissionboundyPolicyArn=arn:aws:iam::xxxxxxxxxxxxx:policy/security_pb"

Using that string, it wants to work, but we get hit by the IAM: Role issues I posted above where it said the account doesn't have rights to create the roles.  We don't want the roles to be created as we've already defined the guardrails and just asking it to use the existing cognito pool.  Hopefully this is a little more concise description.

Thanks again.

**Comment by shchambe** [comment]
We made some changes in the template.yaml file that got us past the role issues, but now it's failing with this error: CloudFormation did not receive a response from   
                                                                                                                                                         your Custom Resource. Please check your logs for 
                                                                                                                                                         requestId                                        
                                                                                                                                                         [b83c9d13-b63b-4215-bf2b-118b4a8d53b6]. If you   
                                                                                                                                                         are using the Python cfn-response module, you    
                                                                                                                                                         may need to update your Lambda function code so  
                                                                                                                                                         that CloudFormation can attach the updated       
                                                                                                                                                         version.

**Comment by shchambe** [comment]
No, you understand exactly what we're doing. Unfortunately, I have no control over that aspect.  The company has other teams that control this, so I have to work within the guardrails.  It's mostly deploying now, just that super unhelpful Custom Resource error for NonceSigningSecret, LambdaCodeUpdate and UserPoolDomainLookup.  Once we get that resolved, I think we'll be in good shape.

**Comment by shchambe** [comment]
I'm still struggling with getting this code to work for what I need.  We're supplying our existing CognitoPool information (Domain, ID, Pool), however, the deployment is trying to create a local pool and use that.  Our CognitoPool is in a different account (Management) whereas everything else is in our nonprod account.  What we're seeing is ClientSecretRetrieval and UserPoolLookupDomain use part of the existing CognitoPool, but it's trying to use the nonprod account and not the management account we're passing in via parameter override.  I'm really at a loss as to how to fix this.  Please, does anyone have any suggestions?

**Comment by ottokruse** [comment]
Published v2.1.1 which should help you, have a look at the notes in the PR #191 and let me know if that helps

**Comment by ottokruse** [comment]
Closing for now. If there’s still an issue, please post back

**Comment by shchambe** [comment]
We just deployed the configuration to Prod.  It's still working great!!
