### ISSUE TITLE
[Enhancement] Allow usage of an existing user Pool

### ISSUE THREAD

**Issue by ottokruse** [aws-samples/cloudfront-authorization-at-edge#19]
It would be great if this app can be wired into an existing user pool.

**Comment by ottokruse** [comment]
That would then make it possible to use a user pool in another region than us-east-1

**Comment by ramy-siha** [comment]
@ottokruse  I was considering how such how we can deploy that solution where the S3 Bucket and the User pool are in a different region.
I did consider using Stack Sets where we will use a stack for us-east-1 for the Lambda functions while the other stack in a different region will have the user pool, yet I didn't find a way to auto mate the stack set deployment using the SAM CLI.
The other approach I did consider is by using the SSM where the template at us-east-1 will reference the User Pool ARN through the SSM as a Custom Resource.

Ofcourse the final approach will be as you mentioned in the README.md by spiting the template.yaml file into two separate files, yet we will have to pass the ARN manually  as parameters , so there is no way to actually automate that flow.

I was hoping to reach a solution where I can pass the different Region as a parameter, where the User Pool and the S3 bucket will get created into that region, while the rest of the Lambda Function will be deployed to the us-east-1 region.

**Comment by ottokruse** [comment]
If not splitting the stack, you would need to implement CFN custom resources to create the S3 bucket and User Pool (and domain and client) in another region than the stack itself. It can be done, but involves some coding.

If splitting the stack, and you want automation still, you need some way to import outputs from one of the stacks into the other stack. Native CFN import-exports cannot cross region, however you could implement a custom resource for it. A custom resource doing only this, would not entail a lot of code.

**Comment by ottokruse** [comment]
DONE: #75
