### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”)

### ISSUE THREAD

**Issue by Dhyanesh97** [aws-samples/cloudfront-authorization-at-edge#197]
![image](https://user-images.githubusercontent.com/89400147/165232792-6751fc6b-f64a-4fe4-ab34-c3c543c4ef01.png)

When I open Cloudfront URL after authenticating with cognito it shows above errors that it is not able to load the page due to security issues.

![image](https://user-images.githubusercontent.com/89400147/165245075-6ff84557-242c-47d2-94e7-b388b70b03d3.png)

How can I modify headers from existing setup to resolve this issue ?
Or any possible solution for this ?

Any help appreciated.

**Comment by Dhyanesh97** [comment]
added Response headers policy to the cloudfront behaviors which resolved the issue.

**Comment by ottokruse** [comment]
Great that you resolved it. If interested, see #73 for some other options to resolve the issue.
