### ISSUE TITLE
Possible Open Redirect (CWE-601) in sample code

### ISSUE THREAD

**Issue by peter-at-work** [aws-samples/cloudfront-authorization-at-edge#205]
This repo provides a sample and has to be copied and built for use in a real environment.  Hence, not exactly a security issue with the project itself.  Is a GitHub issue the right venue to provide details?

**Comment by ottokruse** [comment]
Thanks for asking!

The official answer is:

> Security issue notifications
>
> If you discover a potential security issue in this project we ask that you notify AWS/Amazon Security via our [vulnerability reporting page](http://aws.amazon.com/security/vulnerability-reporting/). Please do not create a public github issue.

Do you want to bounce the issue against me first? Mail me at ottokrus at amazon dot nl

**Comment by ottokruse** [comment]
Fixed in #210
