### ISSUE TITLE
nonce cookies are not expired

### ISSUE THREAD

**Issue by peter-at-work** [aws-samples/cloudfront-authorization-at-edge#206]
After the user has finished signing on and the auth code flows back to the application and has been exchanged for the tokens, the _parse-auth_ Lambda@Edge wants to clear the _nonce_ cookies with these lines:
https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/def3c66e95f2ae5fcd8b04a1e31f27eef56f0091/src/lambda-edge/shared/shared.ts#L445-L451

The generated HTTP response header looks like this:
```
set-cookie: spa-auth-edge-nonce=; Expires=Thu, 01 Jan 1970 00:00:00 GMT
```
Chrome (and potentially other browsers) does not recognize this as an indicator to expire/purge the cookie because the response header is missing other cookie properties.

According to https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.2, the `Path` property may need to be present and match the `Path` property as originally sent when the cookie was created.  Not sure if other cookie properties are also relevant to the matching process.

**Comment by ottokruse** [comment]
Fixed in #207
