### ISSUE TITLE
Node version bump

### ISSUE THREAD

**Issue by kraleva** [aws-samples/cloudfront-authorization-at-edge#235]
Hey, first thanks for the project, you provided. It's really cool ! 

I just wanted to mention, that maybe it might be a good idea to bump the node version of the tsconfig file. Currently, node 20 is already released whereas the project uses the config for node14, which might be suboptimal.

**Comment by ottokruse** [comment]
Had a look myself and it turned out to be more involving because with Node18 the aws-sdk is no longer available in the Lambda runtime enviroment, so you need to include it yourself (or switch to the V3 SDK which is even more involving).
Had an attempt but then ran into this issue https://github.com/npm/cli/issues/4783 when building the React App.

**Comment by ottokruse** [comment]
Updated to Node 16 for now

**Comment by takeshi-mori-ca** [comment]
Thank you for the very helpful sample.
Node.js 16 has been deprecated, are there any plans to update it?

https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/lambda-runtimes.html

**Comment by ottokruse** [comment]
Plans yes, but we didn't get to it yet. If you want to send a PR don't hold back :)

**Comment by scar4me** [comment]
FYI, for anyone looking to deploy these as Lambda's with Node20.x you can already do this with a minor tweak.

To make this work [src/lambda-edge/shared/shared.ts](url)required 2 changes:
#13`import SSM = require("@aws-sdk/client-ssm");`
#183`const getPathParams = await ssm.getParametersByPathCommand(pathParams).promise();`

Then by packaging the provided existing function typescript code with esbuilder with the following tsconfig.json settings:
`"compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "lib": ["ES2022"],
        "module": "ES2022",
        "moduleResolution": "node",
        "target": "ES2022"
      },`

We also now have this packaged for deployment within terraform automation pipelines using this terraform provider: [https://registry.terraform.io/providers/jSherz/node-lambda-packager/latest](url)
And the module var set to:
```
args = [
    "--bundle",
    "--external:@aws-sdk*",
    "--external:axios",
    "--external:cookie",
    "--external:jsonwebtoken",
    "--external:jwks-rsa",
    "--external:./error-page/template.html",
    "--minify",
    "--platform=node",
    "--sourcemap",
    "--target=es2022",
    "--sourcemap=inline",
  ]
```

We are only using the following: check-headers, http-headers, parse-auth, refresh-auth, sign-out functions.
So far this is in initial testing and validations, but this does appear to fully functional and stable.

**Comment by ottokruse** [comment]
Upgraded to Node v20!

https://github.com/aws-samples/cloudfront-authorization-at-edge/releases/tag/v2.2.1
