### ISSUE TITLE
Cognito TAGS

### ISSUE THREAD

**Issue by reisub83** [aws-samples/cloudfront-authorization-at-edge#247]
When running the `sam deploy` with the **--tags LIST** option, Cognito user pool does not inherit tags.

Cloudformation stack, Cloudfront distribution and S3 buckets are ok.

Is it possibile to fix this?

**Comment by ottokruse** [comment]
This propagation is an in-built feature of CloudFormation and is not supported for all AWS services per se unfortunately.

See also: https://repost.aws/knowledge-center/cloudformation-propagate-stack-level-tag
