### ISSUE TITLE
How Do I add User Pool attributes to Cookies?

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [aws-samples/cloudfront-authorization-at-edge#249]
I have a bunch of custom attributes associated with my SAML IDP (example shown below). In the example I have a user attribute called `custom:Brand`. How can I get this value added to the cookies?

Or, is this something I should rather retrieve using Amplify on the frontend?

![image](https://github.com/aws-samples/cloudfront-authorization-at-edge/assets/19767538/44a86539-12b3-47c6-b6d9-8af9a2cb1901)

**Comment by ottokruse** [comment]
You should see them as claims on the ID token, that is in the cookies. Or is that not what you mean ?
