### ISSUE TITLE
Having the ability to tune logs

### ISSUE THREAD

**Issue by pierresouchay** [aws-samples/cloudfront-authorization-at-edge#255]
We are using this service in my company for several frontends.

There are several problems in case of multi-tenancy:

* logs-groups don't have tags (an issue with invoicing)
* it is hard to find logs, because all IDs are random for both lambdas and logs => make it impossible to find the correct logs easily for an application
* not possible to set retention time for logs or additional parameters

I propose here a PR with small modification to enable this: https://github.com/aws-samples/cloudfront-authorization-at-edge/pull/254 => should allow running that efficiently and have a common prefix to quickly identity the logs for an app and allow some tuning (retention logs) as well as applying tags on logs

**Comment by ottokruse** [comment]
We merged #254  and I don't think we can do anything else (see discussion in that PR)
