### ISSUE TITLE
'JavaScript heap out of memory' when running npm run build

### ISSUE THREAD

**Issue by jimboboliver** [aws-samples/cloudfront-authorization-at-edge#274]
On v2.3.0 I have to change the 'webpack' script in package.json from `webpack --progress` to `node --max-old-space-size=16384 node_modules/webpack/bin/webpack.js --progress` otherwise the process runs out of memory. 

Environment: Ubuntu 22.04.4 LTS

As a side note, is the version in package.json is still 2.2.1.

**Comment by ottokruse** [comment]
I don't have that problem and I run this on a box with 16 GB RAM, how much do you have?

> As a side note, is the version in package.json is still 2.2.1.

Ah thanks. Should have no impact but to avoid confusion it should match the release version of course.

**Comment by jimboboliver** [comment]
My machine has 32GB RAM total. I don't think it's the total RAM that's the problem.
Node version: v20.11.1

**Comment by jimboboliver** [comment]
Apologies Otto, I was mistaken on which branch I was running on. The problem was that I had added a top level import of aws-sdk in one of the edge functions.

**Comment by ottokruse** [comment]
NP thanks for reporting back
