### ISSUE TITLE
/signout CORS error with custom cognito domain

### ISSUE THREAD

**Issue by aidden93** [aws-samples/cloudfront-authorization-at-edge#299]
Hi all,

I'm running cognito through a custom domain like https://auth.mydomain.net
The part of my website that requires authentication uses the dashboard subdomain i.e https://dashboard.mydomain.net

I have a Logout button on the dashboard site with a href of https://dashboard.mydomain.net/signout 
/signout is configured as my SignOutUrl

When i click the button i get the error

`Access to XMLHttpRequest at 'https://auth.mydomain.net/logout?logout_uri=https%3A%2F%2Fdashboard.mydomain.net%2F&client_id=MY_CLIENT_ID' (redirected from 'https://dashboard.mydomain.net/signout') from origin 'https://dashboard.mydomain.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I also tried using https://auth.mydomain.net/signout but that didn't work either.

Have i misconfigured something or does cognito simply not support logging out from a different origin? 
I started setting this up 5 months ago so i can't remember the specifics but i think i had issues using the dashboard subdomain as my custom domain and that's why i went with a different subdomain.

This whole project is my first time touching anything relating to aws so please forgive me if the problem is obvious

**Comment by ottokruse** [comment]
Can you share the code of the logout button, how does it work? It should redirect the top-level browser window to https://dashboard.mydomain.net/signout which would itself clear your cookies and redirect to your Cognito Auth domain to signout ([code here](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/src/lambda-edge/sign-out/index.ts)). That does not involve any AJAX requests so should not run into CORS errors. Therefore I do not understand why you get that error.

The error you see indicates that you sign out with AJAX, but that (if you really want that) is not done with the https://auth.mydomain.net/logout URL, but should invoke the Amplify signout method (or you have to implement yourself what that Amplify method does in JS, which is to clear cookies and call Cognito revokeToken())

**Comment by aidden93** [comment]
I'm using HTMX and your question prompted me to test with hx-boost="false" which i was sure i tried before but mustn't have and it's no longer throwing the CORS error so thanks for that.

But now i'm getting redirect_uri not provided and im not sure why. SignOutHandler does have redirectPathSignOut set which i assume is what's used for that.

**Comment by ottokruse** [comment]
Who throws that error, is it Cognito? Need more info to debug with you. The code [does always include a logOut url to Cognito](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/6bf031d080ee781bc9659c5004fd122c1198c07f/src/lambda-edge/sign-out/index.ts#L53). Have a look in the developer panel at the HTTP requests to see what is going on

**Comment by aidden93** [comment]
It does have a logOut url, it's redirect_url that's missing.
The error is 
`GET https://auth.mydomain.net/error?logout_uri=https%3A%2F%2Fdashboard.mydomain.nethttps%3A%2F%2Fwww.mydomain.net&client_id=tvqim56ksd2vf2o9fmklnk9o8 400 (Bad Request)`

Which looks like it's missing actually in there but the redirect_url= bit is missing for some reason.
My site is behind cloudfront so i'm seeing the response come from there

**Comment by ottokruse** [comment]
Well [a Cognito /logout needs either logout uri or redirect uri](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html) and we do set the logout uri.

Can you share a HAR file?

I suspect the logout works for you but immediately redirects you to sign in--which is good but we have to figure out then why redirect URI isn't sent along.

A HAR file that shows the entire redirect flow will likely shed light

**Comment by aidden93** [comment]
Yeah the logout works but the logout_uri seems to be a concatenation of the logout uri and the redirect uri and i can't see what would cause that. Here's the HAR as requested. Had to compress it as github didn't allow it as a .har
[maxibots.net.zip](https://github.com/user-attachments/files/17643639/maxibots.net.zip)

**Comment by ottokruse** [comment]
Thanks

> Yeah the logout works but the logout_uri seems to be a concatenation of the logout uri and the redirect uri and i can't see what would cause that. I'm trying to redirect to the public website rather than the login page

That looks to be the issue. What is the value for `CONFIG.redirectPathSignOut` in your case? Look in the config JSON file in the Lambda function version.

It should be like this:
User goes to <yourdomain>/signout
User is redirect to <cognitodomain>/logout
User is redirected to <yourdomain>/<redirectPathSignOut>

**Comment by aidden93** [comment]
"cognitoAuthDomain": "auth.maxibots.net",
  "redirectPathSignIn": "/parseauth",
  "redirectPathSignOut": "https://www.maxibots.net",
  "signOutUrl": "/signout",
  "redirectPathAuthRefresh": "/refreshauth",


I've tried playing with rediretctPathSignOut but always ends with the same error about redirect_uri missing. 

My user flow:
1. Go to https://dashboard.maxibots.net/
2. Press the logout button which is defined as `<a class="nav-link" href="/signout">Logout</a>`
3. The logout occurs and it redirects to https://auth.maxibots.net/error?logout_uri=https%3A%2F%2Fdashboard.maxibots.nethttps%3A%2F%2Fwww.maxibots.net&client_id=tvqim56ksd2vf2o9fmklnk9o8

**Comment by ottokruse** [comment]
Change `redirectPathSignOut` to `/` (instead of `https://www.maxibots.net/`) and that might solve it.

**Comment by ottokruse** [comment]
`redirectPathSignOut` should be a path, so something that starts with a `/`, likely just a `/` (which is the default).

**Comment by aidden93** [comment]
Okay tried changing to `/`. Made no difference.
Could cognito's custom domain being a different subdomain to that of the main site be the issue?

**Comment by aidden93** [comment]
![image](https://github.com/user-attachments/assets/f629f032-7a8c-4522-b9e4-98ec3459d054)
![image](https://github.com/user-attachments/assets/88f8f3f3-1fe1-410e-82d4-7d864bfb91cf)

**Comment by aidden93** [comment]
[maxibots.net.zip](https://github.com/user-attachments/files/17645180/maxibots.net.zip)

**Comment by ottokruse** [comment]
Make sure the full sign out URL is what you use as Allowed sign-out URL in the app client, so add https://dashboard.maxibots.net/ (your CloudFront URL + redirectPathSignOut)

**Comment by ottokruse** [comment]
Then .... it should work, I think

**Comment by aidden93** [comment]
And that worked! I had that in there earlier as a test before changing the redirectPathSignOut and removed it when it didn't work.
Thank you! Much appreciated.
So if i want the redirect to go to a different subdomain would i need to setup a behaviour on say /logoutredirect that triggers a redirect to https://www.maxibots.net?

**Comment by ottokruse** [comment]
Nice!

> So if i want the redirect to go to a different subdomain would i need to setup a behaviour on say /logoutredirect that triggers a redirect to https://www.maxibots.net/?

yes that works! Or try a CloudFront function (cheaper and faster, but it may not work because we also have Lambda@edge in place and they can't always co-exist).

Or, less nice perhaps but also simple, a file on S3 at that path:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirect</title>
    <script>
        // Redirect to the target URL
        window.location.href = "https://example.com";
    </script>
</head>
<body>
    <p>If you are not redirected, <a href="https://example.com">click here</a>.</p>
</body>
</html>

```

**Comment by aidden93** [comment]
Perfect, thanks again
