### ISSUE TITLE
Is the 'dummy-origin' removable, using the 'protected-bucket' instead?

### ISSUE THREAD

**Issue by voodooGQ** [aws-samples/cloudfront-authorization-at-edge#35]
Are there any downfalls to completely omitting the `dummy-origin` from the distribution and instead just pointing it directly at the `protected-bucket`?

In another related [issue](https://github.com/aws-samples/cloudfront-authorization-at-edge/issues/23#issuecomment-586893742) the following was mentioned:

> The dummy origin "example.org" can remain there, as it is the origin behind the Lambda@Edge functions for parseAuth and such; they will always respond to the request instead of allowing the request to pass through to the origin. Hence "dummy origin", it is there because a CloudFront behavior needs to have an origin, but requests will never be forwarded to it.

The above makes me wonder why a `dummy-origin` is needed if the requests will never be forwarded to it?

Thank you!

**Comment by ottokruse** [comment]
It's a matter of preference. For me the dummy origin makes sense, as it clearly shows some URL patterns to be handled solely by Lambda@Edge, never by the actual origin. But you could point those behaviors also at the protected-origin, I see no downfall.
