### ISSUE TITLE
Export significant stack outputs to allow cross-stack referencing

### ISSUE THREAD

**Issue by iuliu-b** [aws-samples/cloudfront-authorization-at-edge#36]
Exporting more of the stack's outputs would allow users to more easily integrate their own CF stacks with the application. I'm particularly interested in `S3Bucket` and `UserPoolId`. These would allow me to:

1. Configure my stack to deploy my own front-end assets to the existing S3 bucket, and

1. Create an ID pool on top of the existing user pool

respectively. As-is, if I want to do these things via CF I need to manually create mappings for the bucket and user pool.

**Comment by ottokruse** [comment]
Sure, good idea. Send a PR for it? Like #14

**Comment by ottokruse** [comment]
Will be fixed in #57
