### ISSUE TITLE
Access denied from sample SPA

### ISSUE THREAD

**Issue by alexolivero** [aws-samples/cloudfront-authorization-at-edge#51]
Hello,

I deployed the sample app from the AWS Serverless Application Repository.
Upon navigating to the URL for the CloudFront distribution, I log into my Cognito User Pool, update my temporary password, and I get a 403 Access Denied.

I checked into the /parseAuth endpoint, seems there's some issue here. My Lambda logs show nothing for the parseAuth function (it says there was an error loading Log Streams). I tried hitting parseAuth directly in my browser by supplying the code and state like this:

https://{cloudfrontID}.cloudfront.net/parseauth?code={CODE}&state={STATE}

The result was:

Bad Request
ERROR: Error: HTTP POST to https://auth-1fdb0555.auth.us-east-1.amazoncognito.com/oauth2/token failed

Is this some issue with the parseAuth Lambda function, or something else entirely?

**Comment by ottokruse** [comment]
Hi, thanks for trying this solution.

I just deployed myself again to make sure, but it works for me.

If the issue is in parseAuth, please have a look at the logs. The logs are in the region closest to you (not per se the stack region, probably another). Using the CloudFront monitoring console you can locate the parseAuth lambda and see what region it was invoked in, and go to the logs in that region.

Let me know what the logs say.

BTW just 403 ? What is the entire stack-tract / error message?

**Comment by rpattcorner** [comment]
I'm seeing a similar issue -- in this case using the reuse-auth-only example, which I've integrated into a simple stack so I can control bucket naming and the like.  

In the browser I get a generic XML access denied message:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3AE89A4445051297</RequestId>
```
Looking at the parseAuthHandler logs in CWatch Logs I see:

` 3c9a06ab-c6c6-438d-badd-7851ef7c6b61	ERROR	HTTP POST to https://auth-8964c213.auth.us-east-1.amazoncognito.com/oauth2/token failed (attempt 1):`

and shortly thereafter a timeout:

```
2020-05-08T21:15:57.817Z	3c9a06ab-c6c6-438d-badd-7851ef7c6b61	ERROR	Error: write ETIMEDOUT
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
    at writevGeneric (internal/stream_base_commons.js:132:26)
    at TLSSocket.Socket._writeGeneric (net.js:782:11)
    at TLSSocket.Socket._writev (net.js:791:8)
    at doWrite (_stream_writable.js:440:12)
    at clearBuffer (_stream_writable.js:558:5)
    at TLSSocket.Writable.uncork (_stream_writable.js:337:7)
    at ClientRequest._flushOutput (_http_outgoing.js:861:10)
    at ClientRequest._flush (_http_outgoing.js:830:22)
    at _http_client.js:315:47 {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'write',
  config: {
    url: 'https://auth-8964c213.auth.us-east-1.amazoncognito.com/oauth2/token',
    method: 'post',
    data: 'grant_type=authorization_code&client_id=2fpvplunph5vc3cm2pk83sgh58&redirect_uri=https%3A%2F%2Fd19ix9pdn8z7j4.cloudfront.net%2Fparseauth&code=8f7e1f64-e73b-44f5-af7d-004ce2b95431&code_verifier=1-5XuGs_7WnKgY0P81w-zvK7BFqL_GkkSAnRQMVt0Qe',
  ...stuff
```

**Comment by rpattcorner** [comment]
And an interesting bit of mystery ...

Temporarily making the target bucket public access via bucket policy allows access, so apparently it's a real permissions fail.  And even stranger ...

Subsequently disabling the public access allows access to continue, even from another browser, which should have no caching or cookies.  No invalidation, but I can't see what CloudFront caching could have to do with it...

**Comment by bpgould** [comment]
I have the same issue when deploying with following config:

`resource "aws_serverlessapplicationrepository_cloudformation_stack" "cloudfront_authorization_at_edge" {
  name             = "CloudFrontAuthorizationAtEdge"
  application_id   = "arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge"
  semantic_version = "2.3.0"
  capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_RESOURCE_POLICY",
  ]

  parameters = {
    # Uncomment and modify the parameters as needed
    # AdditionalCookies: "{}"
    AlternateDomainNames : "private.mydomain.com"
    # CloudFrontAccessLogsBucket: ""
    # CookieCompatibility: "amplify"
    # CookieSettings: "{\"idToken\": null,\"accessToken\": null,\"refreshToken\": null,\"nonce\": null}"
    # CreateCloudFrontDistribution : "true"
    # CustomOriginDomainName: ""
    # CustomOriginHeaderName: ""
    # CustomOriginHeaderValue: ""
    DefaultRootObject : ""
    EmailAddress : "email@gmail.com"
    EnableSPAMode : "false"
    # HttpHeaders: "{\"Content-Security-Policy\": \"default-src 'none'; img-src 'self'; script-src 'self' https://code.jquery.com https://stackpath.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; object-src 'none'; connect-src 'self' https://*.amazonaws.com https://*.amazoncognito.com\",\"Strict-Transport-Security\": \"max-age=31536000; includeSubdomains; preload\",\"Referrer-Policy\": \"same-origin\",\"X-XSS-Protection\": \"1; mode=block\",\"X-Frame-Options\": \"DENY\",\"X-Content-Type-Options\": \"nosniff\"}"
    # LogLevel: "none"
    OAuthScopes : "phone,email,profile,openid,aws.cognito.signin.user.admin"
    OriginAccessIdentity : "${aws_cloudfront_origin_access_identity.oai.id}"
    # PermissionsBoundaryPolicyArn: ""
    # RedirectPathAuthRefresh: "/refreshauth"
    # RedirectPathSignIn: "/parseauth"
    # RedirectPathSignOut: "/"
    # ResourceSuffix: ""
    # RewritePathWithTrailingSlashToIndex: "false"
    S3OriginDomainName : "something.s3.us-east-2.amazonaws.com"
    # SignOutUrl: "/signout"
    # UserPoolArn : ""
    # UserPoolAuthDomain : ""
    # UserPoolClientId : ""
    # UserPoolClientSecret: ""
    # UserPoolGroupName: ""
    # Version: "2.3.0"
    # WebACLId: ""
  }
}`

when navigating to the CloudFront Distribution URL I get:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E5Q5TY2V8N7SFAHW</RequestId>
<HostId>xM7ISQL6LsSlrwZ5IKBKsUxR+LEZMdpINQM2ZTBU5J1owOcPSSe0o84yj1cx9MYVkE21xOzr19HhCFJi2OuFjw==</HostId>
</Error>`


When investigating the ParseAuth or HttpHeadersHandler, etc Lambda I see in the console:

`There was an error while making a request to StartQuery
Log group '/aws/lambda/serverlessrepo-CloudFrontAuthoriz-ParseAuthHandler-UUKhV0aiSBqS' does not exist for account ID '547...' (Service: AWSLogs; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 292cb6cb-488f-4d20-a52f-ec09315a9953; Proxy: null)`
