### ISSUE TITLE
New refresh token.

### ISSUE THREAD

**Issue by BartoGabriel** [aws-samples/cloudfront-authorization-at-edge#64]
When the token expires and refresh the new token, shouldn't the new refresh token also be updated?

Currently only the id_token and access_token are updated:
https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/src/lambda-edge/refresh-auth/index.ts#L43

**Comment by ottokruse** [comment]
Hi Gabriel. That is intended. The refresh token will remain the same.

The refresh token cannot be used to refresh itself. Thereby the expiry date of the refresh token is the ultimate date when the user has to sign in again.

**Comment by BartoGabriel** [comment]
Thanks Otto, so it is not a mistake, I did not interpret how it worked.

I usually refresh all tokens indefinitely as long as the user is active. When the user stops being active (does not access the web) is when the lifetime of the refresh token begins to run. For example, if someone is using github continuously, the session never expires, it expires when for an X time it is not used.

**Comment by ottokruse** [comment]
Yeah you're right, maybe that is a better strategy!

**Comment by ottokruse** [comment]
Don't hesitate to send a PR! (just saying 😄 )

**Comment by ottokruse** [comment]
Had a look into this and had to refresh my memory, found that Cognito indeed does *not* return a refresh token when refreshing tokens––Cognito only returns a new ID and Access token then.

Which makes total sense to me, the expiry date of the refresh token governs how long it is valid for (can set it to 10 years max).

So, closing this ticket as I believe there is no development opportunity for this solution here.
