### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues in check-auth

### ISSUE THREAD

**Issue by dilippatidar123** [aws-samples/cloudfront-authorization-at-edge#67]
Hello,

I am getting following error in check-auth lambda function, Using latest code with node js 12.x version.

**2020-07-17T11:37:44.524Z	e3eb0320-90bb-4930-a588-f56ed4f273de	ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.**

Is this some issue with reference lib in check-auth Lambda function ?  Please suggest.

Thanks,
Dilip

**Comment by ottokruse** [comment]
I think this dependency is the culprit: https://github.com/auth0/node-jwks-rsa/blob/d0c5787fd9ea51a4f7cb28ea71b2522ce3e23727/src/utils.js

They do a few times `new Buffer(...)` and would probably appreciate a PR to use the modern notation.

**Comment by dilippatidar123** [comment]
Thanks @ottokruse

**Comment by ottokruse** [comment]
Fixed upstream and included in #75
