### ISSUE TITLE
[Question] Does this work with the default Cognito UI?

### ISSUE THREAD

**Issue by fred97855** [aws-samples/cloudfront-authorization-at-edge#72]
I don't know if I have done something stupid - but I have extracted the lambda logic out and integrated it into a very basic 
Cloudfront hosted website.

Everything works as expected, unless you are a new user trying to register using the hosted UI, when once you have filled in the form you are sent to `/error` page on the hosted UI. The user is added to the pool.

So I cant understand whats going on! The logic for stopping, signing out, refreshing etc all work fine. Is this meant for use with the hosted Cognito UI?

Cheers

**Comment by ottokruse** [comment]
Hi! Can you provide some more details on what goes wrong?

- What is the error message from the Cognito hosted UI?
- What do you see in the logs of the Lambda@Edge function? Check the logs of the checkAuth and parseAuth functions please?

Could you try creating the user in the AWS Console first and then sign in? (Instead of "self registering" the user through the Hosted UI). Does that work?

**Comment by fred97855** [comment]
Hi @ottokruse,
I've attached a screenshot of the error, as you can see its not very helpful :(
There don't appear to be able logs generated by those, when using the hosted UI
![image](https://user-images.githubusercontent.com/52532600/89546075-0e4ed800-d7fc-11ea-9b1d-ef711272b1bb.png)
Is there a way to see logs from the hosted UI?

**Comment by ottokruse** [comment]
You can't see the logs from the hosted UI––it should return it's error clearly to you. Check if you maybe see it in the URL, Cognito sometimes puts the error there, as a query param.

For debugging this I recommend to open your Browser's network panel (press F12) and inspect all the redirects happening. Have a look at the HTTP requests: which URL's do they go to, which redirects are happening, does anything seem to be off?

**Comment by fred97855** [comment]
Hi @ottokruse - I finally managed to track down the cause. I had extracted all this into a Terraform project, and somehow Terraform was deploying the configuration for "How do you want your end users to sign in?" Like nothing was selected (not even sure how thats possible?) So I think when the user was being registered, something within Cognito itself died causing the error. Now it has config options selected, it works perfectly.

Thanks

**Comment by rpattcorner** [comment]
@fred97855 , if you see this comment I'd very much like to see how you implemented this framework in Terraform!

**Comment by fred97855** [comment]
@rpattcorner I will put together an example and send over a repo asap :)
