### ISSUE TITLE
Deploy to different regions

### ISSUE THREAD

**Issue by lewisrobbins** [aws-samples/cloudfront-authorization-at-edge#80]
Hi I need to deploy some parts to another region such as Cognito. Currently I have to deploy everything to us-east-1 due to the hard constraint on Lambda@Edge. 

Is there anyway to get around this? Maybe by copying Lambdas from one region to another? I've tried breaking the CloudFormation up in 2 (with Lambdas and Cloudfront in one) and the others in another script then using `!ImportValue` but that's messy.

**Comment by ottokruse** [comment]
Hi @lewisrobbins ,

> Is there anyway to get around this?

For Lambda@Edge: no there is no way around this, needs to be us-east-1. 

Maybe you've seen this already, but the good news is that last week we've released v2.0.0 of this serverless app here, that makes it easy to use a Cognito Pool from another region. See the docs here: [Deployment region](https://github.com/aws-samples/cloudfront-authorization-at-edge#deployment-region)

Note also that imports do not work across regions. Alternative: for another deployment I worked on, we wrote a custom resource to collect the stack outputs from a stack in one region, so we can use them easily in a stack in another region
