### ISSUE TITLE
Possible unused code in generateCookieHeaders?

### ISSUE THREAD

**Issue by troyready** [aws-samples/cloudfront-authorization-at-edge#89]
I feel like I'm probably missing something obvious, but it looks like some of the [expiration logic in _generateCookieHeaders](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/5ea0cdc503b33d5845ab3d52c2e9fd2e843c83e8/src/lambda-edge/shared/shared.ts#L364-L366) references keys that don't exist.

I.e. the [cookies object](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/5ea0cdc503b33d5845ab3d52c2e9fd2e843c83e8/src/lambda-edge/shared/shared.ts#L334-L344) is defined with certain keys just above it, and they don't include keys like `spa-auth-edge-nonce`.

**Comment by ottokruse** [comment]
Hi Troy. There are other places besides that helper function where cookies can be set. You can find the other places by searching the codebase for "set-cookie". Most notably, checkAuth lambda sets cookies too, such as spa-auth-edge-nonce.

**Comment by troyready** [comment]
@ottokruse from what I can see, the _generateCookieHeaders function wouldn't reference the cookies created by those other functions.

[The line in question](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/c99f34185384b47cfb2273730dbcd380de492d12/src/lambda-edge/shared/shared.ts#L444) references the cookie object defined in the same function, either [here](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/c99f34185384b47cfb2273730dbcd380de492d12/src/lambda-edge/shared/shared.ts#L379) or [here](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/c99f34185384b47cfb2273730dbcd380de492d12/src/lambda-edge/shared/shared.ts#L400).

I think what's happening now is `cookies[key] = expireCookie(cookies[key]);` is resolving to `cookies[key] = expireCookie(null);`, right? Might be better to be more explicit i.e. `cookies[key] = expireCookie();`?

**Comment by ottokruse** [comment]
> Might be better to be more explicit i.e. cookies[key] = expireCookie();

Yeah indeed!
Wanna send a PR for it? Always looking to motivate possible contributors :)
